### ISSUE TITLE
Windows下重定向输入输出会导致乱码

### ISSUE THREAD

**Issue by chr233** [chr233/RCNB.python#2]
应该是Windows控制台默认代码页是`gbk`的原因，暂时不知道如何解决。

**Comment by liggest** [comment]
如果是部分字符显示为“□□”之类的，猜测可能是字体问题…
我在cmd里面，字体是黑体，编码结果就有些方框和显示不出来的部分；
vscode的终端（powershell）里面是能正确显示出来的，字体是Consolas（大概）
然后这俩的编码应该都是gbk
把乱码的部分复制到utf-8编码的文件里，甚至浏览器链接栏之类的地方，应该能显示出正确结果

**Comment by chr233** [comment]
> 你可以试试，不是字体问题，是输出utf8字节流然后被当成gbk解码，就乱码了。Linux下正常，把Windows默认编码方式改成utf8也正常。

**Comment by liggest** [comment]
我这边是这个样子的
根据百度，936应该是gbk，65001应该是utf8
这是cmd里面的结果
![cmd gbk.png](https://i.loli.net/2021/06/17/8wdOoxfp7jm3J1S.png)
![cmd utf-8.png](https://i.loli.net/2021/06/17/ZCOmX7hfliJ2YIT.png)
这是vscode里面的结果
![vscode gbk.png](https://i.loli.net/2021/06/17/6uyYf9cxqMQlShr.png)

**Comment by chr233** [comment]
> 我这边是这个样子的
> 根据百度，936应该是gbk，65001应该是utf8
> 这是cmd里面的结果
> ![cmd gbk.png](https://camo.githubusercontent.com/b91ad6d7f7c4748ccfc58c6b2ab34f304cf43b0a9e077a8734625ad147924859/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31372f3877644f6f786670376a6d334a31532e706e67)
> ![cmd utf-8.png](https://camo.githubusercontent.com/93001e58edbdfce645bdcc49e7a86aef75eb31c8c7c76d753a09fcac8800f6f6/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31372f5a434f6d583768666c694a325949542e706e67)
> 这是vscode里面的结果
> ![vscode gbk.png](https://camo.githubusercontent.com/72d3e2bee24d790d3f3e8b4daea684e163ab566f01f3ac42d13c12cb884ed9e9/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31372f3675795966396378714d516c5368722e706e67)

你这个是直接输出，跟重定向没有关系，重定向乱码是这个样子：
![image](https://user-images.githubusercontent.com/13798576/122329196-91d06e00-cf63-11eb-9aac-c8e324029fec.png)
![image](https://user-images.githubusercontent.com/13798576/122329255-a876c500-cf63-11eb-88ec-572f82f75d25.png)

**Comment by liggest** [comment]
抱歉，是我搞错了…
这边一直在用cmd测试，输出重定向到文件，打开之后内容是正常的，就也没太在意
又试了一下发现，cmd下
`echo 测试 | python -m rcnb`
反而会出问题

**Comment by liggest** [comment]
于是用cmd和powershell都试了一下，得到的文件是不一样的
![cmd issue01.png](https://i.loli.net/2021/06/17/oGwvshfMdy6ZV54.png)
![powershell issue01.png](https://i.loli.net/2021/06/17/jfk4OMdazibxy3E.png)
cmd得到的`test.txt`，内容是编码后的正常结果，文件编码是UTF-8
powershell得到的`test2.txt`，内容和终端里一样是乱码，文件编码是UCS-2
![cmd issue02.png](https://i.loli.net/2021/06/17/IgFPEOj19UC8DxG.png)
![powershell issue02.png](https://i.loli.net/2021/06/17/PbCrALVykoQwD9X.png)
所以我觉得是powershell的问题……

**Comment by chr233** [comment]
> 于是用cmd和powershell都试了一下，得到的文件是不一样的
> ![cmd issue01.png](https://camo.githubusercontent.com/6298b2957f0d84404022d6146ec5812c845e1689d0ccfc4f915a2b5907baff18/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31372f6f4777767368664d6479365a5635342e706e67)
> ![powershell issue01.png](https://camo.githubusercontent.com/ca711e0c4a3e31f37ab021b8d9781e9a698fdaefbb6c01959d9d41a4e0bdf6f8/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31372f6a666b344f4d64617a6962787933452e706e67)
> cmd得到的`test.txt`，内容是编码后的正常结果，文件编码是UTF-8
> powershell得到的`test2.txt`，内容和终端里一样是乱码，文件编码是UCS-2
> ![cmd issue02.png](https://camo.githubusercontent.com/f9757d27bc73177619ea931ff88ca6197bcd004afdce17679a79afbdeadeb38e/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31372f49674650454f6a31395543384478472e706e67)
> ![powershell issue02.png](https://camo.githubusercontent.com/68e21b55797e0c41f8486ee78a57a347f8550c87b0e2a78aa208bee36cfa2e28/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30362f31372f50624372414c56796b6f51774439582e706e67)
> 所以我觉得是powershell的问题……

CMD下UTF-8模式一切正常，GBK模式显示有问题，但是可以正常解码

![image](https://user-images.githubusercontent.com/13798576/122390855-01b31880-cfa5-11eb-8cc6-22a50e9ebe48.png)

![image](https://user-images.githubusercontent.com/13798576/122390985-20191400-cfa5-11eb-834c-c63979c60bc6.png)

POWERSHELL下GBK模式显示有问题，也无法解码，UTF-8模式也不行

![image](https://user-images.githubusercontent.com/13798576/122391449-987fd500-cfa5-11eb-9b5a-3f1c19238982.png)

![image](https://user-images.githubusercontent.com/13798576/122391496-a7668780-cfa5-11eb-92a4-1b82d74ed956.png)

**Comment by liggest** [comment]
所以其实cmd还是挺能用的233
感觉是powershell本身的问题，可以通过不用powershell重定向来解决(

**Comment by chr233** [comment]
> 所以其实cmd还是挺能用的233
> 感觉是powershell本身的问题，可以通过不用powershell重定向来解决(

并不是，原因是输出的是utf8字节流，被windows当成gbk解码了，powershell和cmd的区别是cmd直接把字节流传走了，而powershell自己做了一次转码

**Comment by liggest** [comment]
> > 所以其实cmd还是挺能用的233
> > 感觉是powershell本身的问题，可以通过不用powershell重定向来解决(
> 
> 并不是，原因是输出的是utf8字节流，被windows当成gbk解码了，powershell和cmd的区别是cmd直接把字节流传走了，而powershell自己做了一次转码

所以我的意思是，cmd虽然输出乱码但至少能正常完成编码解码，目前的程序不作修改也还算是能用的
powershell这边自己转成了类似utf-16的东西，导致重定向后没法得到正确的编解码结果，就有点怪了…
感觉这种问题要在python程序中完全解决，会需要挺复杂的逻辑（我经验比较少，对此没有什么头绪orz）
不知是否有第三方库可以搞定这种问题？其他RCNB实现好像也没管这种事情吧…？
